// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNkeJkkBqczzRCnzXaUX2UtNbVW_bkxO0',
    appId: '1:1033627124457:web:941619c2a39cd24fea6678',
    messagingSenderId: '1033627124457',
    projectId: 'fasmail-7c4de',
    authDomain: 'fasmail-7c4de.firebaseapp.com',
    storageBucket: 'fasmail-7c4de.firebasestorage.app',
    measurementId: 'G-DXDP3TLQ25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB57oxTpd55tnOhiD_MXH0CA2mXjNcHwyA',
    appId: '1:1033627124457:android:fb802e260dc6c3d9ea6678',
    messagingSenderId: '1033627124457',
    projectId: 'fasmail-7c4de',
    storageBucket: 'fasmail-7c4de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3iDz5hB3hBZAtASwvapa5fb4AQjK-Lyw',
    appId: '1:1033627124457:ios:dbe74ecb803e63a9ea6678',
    messagingSenderId: '1033627124457',
    projectId: 'fasmail-7c4de',
    storageBucket: 'fasmail-7c4de.firebasestorage.app',
    iosBundleId: 'com.example.fasmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3iDz5hB3hBZAtASwvapa5fb4AQjK-Lyw',
    appId: '1:1033627124457:ios:dbe74ecb803e63a9ea6678',
    messagingSenderId: '1033627124457',
    projectId: 'fasmail-7c4de',
    storageBucket: 'fasmail-7c4de.firebasestorage.app',
    iosBundleId: 'com.example.fasmail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNkeJkkBqczzRCnzXaUX2UtNbVW_bkxO0',
    appId: '1:1033627124457:web:941619c2a39cd24fea6678',
    messagingSenderId: '1033627124457',
    projectId: 'fasmail-7c4de',
    authDomain: 'fasmail-7c4de.firebaseapp.com',
    storageBucket: 'fasmail-7c4de.firebasestorage.app',
    measurementId: 'G-DXDP3TLQ25',
  );
}
